version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20210929
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks: 
      - test-automation-setup


  chrome:
    image: selenium/node-chrome:3.141.59-20210929
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks: 
      - test-automation-setup


  firefox:
    image: selenium/node-firefox:3.141.59-20210929
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks: 
      - test-automation-setup

  mvn-tests:
    build: 
      context: .
      dockerfile: ./Dockerfile-mvn

    networks: 
      - test-automation-setup
    depends_on:
      - selenium-hub
      - firefox
      - chrome
    volumes:
      - $PWD/test-results:/docker/test-results
    command: >
      bash -c "
      sleep 25s
      && mvn clean test -Dbrowser=chrome -DgridURL=selenium-hub:4444
      && mvn io.qameta.allure:allure-maven:report
      && rm -rf test-results/* 
      && cp -r target/site/allure-maven-plugin test-results
      "


networks: 
    test-automation-setup: 
        external: true

  